// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package grpc.service.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.service.hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   * @return The request.
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   * @return The bytes for request.
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
