// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package grpc.service.hello;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_service_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_service_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_service_hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_service_hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\022grpc.service.hello\"\037\n\014Hel" +
      "loRequest\022\017\n\007request\030\001 \001(\t\"B\n\rHelloRespo" +
      "nse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\020\n\010" +
      "response\030\003 \001(\t2c\n\014HelloService\022S\n\014helloS" +
      "ervice\022 .grpc.service.hello.HelloRequest" +
      "\032!.grpc.service.hello.HelloResponseB\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_service_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_service_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_service_hello_HelloRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_grpc_service_hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_service_hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_service_hello_HelloResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
