// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package grpc.service.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.service.hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string response = 3;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 3;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
