// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemparam.proto

package grpc.service.param;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.service.param.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string createdDate = 5;</code>
   * @return The createdDate.
   */
  java.lang.String getCreatedDate();
  /**
   * <code>string createdDate = 5;</code>
   * @return The bytes for createdDate.
   */
  com.google.protobuf.ByteString
      getCreatedDateBytes();

  /**
   * <code>string modifiedDate = 6;</code>
   * @return The modifiedDate.
   */
  java.lang.String getModifiedDate();
  /**
   * <code>string modifiedDate = 6;</code>
   * @return The bytes for modifiedDate.
   */
  com.google.protobuf.ByteString
      getModifiedDateBytes();

  /**
   * <code>string createdBy = 7;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string createdBy = 7;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>string modifiedBy = 8;</code>
   * @return The modifiedBy.
   */
  java.lang.String getModifiedBy();
  /**
   * <code>string modifiedBy = 8;</code>
   * @return The bytes for modifiedBy.
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();
}
