// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemparam.proto

package grpc.service.param;

public interface DetailParamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.service.param.DetailParamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.service.param.Result result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.grpc.service.param.Result result = 1;</code>
   * @return The result.
   */
  grpc.service.param.Result getResult();
  /**
   * <code>.grpc.service.param.Result result = 1;</code>
   */
  grpc.service.param.ResultOrBuilder getResultOrBuilder();

  /**
   * <code>.grpc.service.param.Data data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.grpc.service.param.Data data = 2;</code>
   * @return The data.
   */
  grpc.service.param.Data getData();
  /**
   * <code>.grpc.service.param.Data data = 2;</code>
   */
  grpc.service.param.DataOrBuilder getDataOrBuilder();
}
